CREATE TABLE public.app_user (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    display_name character varying(255),
    email_verified boolean NOT NULL,
    google_id character varying(255),
    last_login timestamp(6) without time zone,
    password character varying(255),
    role character varying(255),
    username character varying(255)
);


--
-- Name: maintenance_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maintenance_record (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    date date,
    deleted_at timestamp(6) without time zone,
    description_json text,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    vehicle_id uuid NOT NULL
);


--
-- Name: maintenance_record_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maintenance_record_aud (
    id uuid NOT NULL,
    rev integer NOT NULL,
    revtype smallint,
    created_at timestamp(6) without time zone,
    date date,
    deleted_at timestamp(6) without time zone,
    description_json text,
    title character varying(255),
    updated_at timestamp(6) without time zone,
    vehicle_id uuid
);


--
-- Name: media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    file_type character varying(255),
    model_id uuid,
    model_type character varying(255)
);


--
-- Name: revinfo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revinfo (
    rev integer NOT NULL,
    revtstmp bigint
);


--
-- Name: revinfo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.revinfo_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: secure_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.secure_token (
    id integer NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    purpose character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: secure_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.secure_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.secure_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    display_name character varying(255) NOT NULL,
    make character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    registration character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    year integer NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: vehicle_aud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_aud (
    id uuid NOT NULL,
    rev integer NOT NULL,
    revtype smallint,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    display_name character varying(255),
    make character varying(255),
    model character varying(255),
    registration character varying(255),
    updated_at timestamp(6) without time zone,
    year integer,
    user_id uuid
);



ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: maintenance_record_aud maintenance_record_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_record_aud
    ADD CONSTRAINT maintenance_record_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: maintenance_record maintenance_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_record
    ADD CONSTRAINT maintenance_record_pkey PRIMARY KEY (id);


--
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- Name: revinfo revinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revinfo
    ADD CONSTRAINT revinfo_pkey PRIMARY KEY (rev);


--
-- Name: secure_token secure_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secure_token
    ADD CONSTRAINT secure_token_pkey PRIMARY KEY (id);


--
-- Name: secure_token uk1vnojtqwxyii8kinnsohdknhw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secure_token
    ADD CONSTRAINT uk1vnojtqwxyii8kinnsohdknhw UNIQUE (token);


--
-- Name: vehicle_aud vehicle_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_aud
    ADD CONSTRAINT vehicle_aud_pkey PRIMARY KEY (rev, id);


--
-- Name: vehicle vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_pkey PRIMARY KEY (id);


--
-- Name: vehicle fk1rmuyse7b5h3k60p0hv5grgqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT fk1rmuyse7b5h3k60p0hv5grgqr FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE RESTRICT;


--
-- Name: secure_token fkeh62p10xplcohnme79hkl335w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secure_token
    ADD CONSTRAINT fkeh62p10xplcohnme79hkl335w FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: maintenance_record_aud fkeq7ki9e454726bddah92rydmu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_record_aud
    ADD CONSTRAINT fkeq7ki9e454726bddah92rydmu FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: vehicle_aud fkgxoo2pqewospjrbe04qvqfspo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_aud
    ADD CONSTRAINT fkgxoo2pqewospjrbe04qvqfspo FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: maintenance_record fkkd5e94ju00fldfwf35mvkrxnd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_record
    ADD CONSTRAINT fkkd5e94ju00fldfwf35mvkrxnd FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id) ON DELETE CASCADE;

