CREATE TABLE public.car_model (
    id integer NOT NULL,
    make character varying(255) NOT NULL,
    model character varying(255) NOT NULL
);

ALTER TABLE public.car_model ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);